### ISSUE TITLE
Subindexing strings that contain " or ' fails If surrounded by ' or " respectively

### ISSUE THREAD

**Issue by mpourmpoulis** [mpourmpoulis/PythonVoiceCodingPlugin#18]
## Description

**General Information**

Plug-In Version: v0.1.2,develop, probably the entire 0.1.x Is affected

**Queries Affected**

- [ ] Argument

- [ ] Big Roi

- [x] Sub Indexing
	- [ ] only dedicated Subindexing commands
	- [x] also affect suffixes

- [ ] Operations
	- [ ] Paste
	- [ ] Delete
	- [ ] Swap
	- [ ] Edit
	- [ ] Prefix

- [ ] Collections

picking up parts of certain types of strings fails! this also causes commands of the for `smart string 2` to fail if problematic strings are within the search space

**Response To Command**

- [x] the command fails/nothing happens at all

- [ ] the command select/operates on a wrong result,
	- [ ] that did not match your positional description (e.g. grabs an ROI one line above or below the one you wanted)
	- [ ] did not match the type of result you are looking for(e.g. you wanted an assertion message but you got assertion condition)
	- [ ] or maybe the result was of the correct type and position but it was selected improperly(e.g. you asked for the parameter list of function but the last parameter was not selected)
	- [ ] or maybe things are working fine when trying to select a region as a whole but start breaking when you try access smaller pieces of it
	- [ ] or perhaps the command did find the correct result but perhaps the alternatives included regions they should not or vice versa. (for instance because the command searched the entire code instead of just the current function or vice versa)

- [ ] somehow the whole preserving the current state(alternatives,origin,initial_origin and so on) was messed up by the command! For instance,
	- [ ] track was lost of initial originand things were pasted back onto the wrong position
	- [ ] alternatives were changed when they were supposed not to!(for instance prefix operations are not supposed to do this)

- [ ] the command seems to select/operates on a random result

- [ ] the command has some other unintended behavior

**Context In Which It Appears**

Does the problem seem to appear or disappear only some of the time? Does there seem to be

- [ ] spatial context/correlation with the cursor? for instance
	- [ ] is it affected by adjustments to the cursor position?()
	- [ ] does it make a difference whether you have selected some text or not?
	- [ ] does the problem appear only when you're going in one direction?
	- [ ] does it have to only do with multiple cursors?
	- [ ] or perhaps when switching back-and-forth between single and multiple cursors?

- [ ] a temporal context?
	- [ ] does it appear only right after selection query was executed?
	- [ ] does it appear only if no one other selection query was executed since the last edit?
	- [ ] does it appear only after executing an operation(paste,delete,swap)?
	- [ ] does it appear when you perform manual editing between commands?

- [x] correlation with a pattern in the code? Such a pattern might be structural, sometimes lexical,in some cases even some piece of incomplete code that was not handled properly. A strong indicator for such a case when introducing small changes to the code has things from working perfectly into breaking. In case you have identified(or you have any suspicion about) this pattern(or maybe patterns), does the error occure when it appears
	- [ ] on the target of the query? (For instance there was a bug at some point that sometimes prevented you from selecting arguments from function calls inside with statements)
	- [ ] on the origin of the query?
	- [ ] in between them perhaps?
	- [ ] somewhere inside to the current function/class/indentation block/...
	- [ ] anywhere in the code :)

it seems that it does not like at all, when `"` or `'` are inside a string that is surrounded by `'`,`"` respectively

```python
'" "'
"'b'"
"Bob's"
"\"ab\'"
```

even if  they are escaped. In contrast these actually works

```python
"\"ab\""
"\"ab"
'a\'b'
```

the same applies for triple quoted strings as well!

```python
'''a\"b'''
```

**Error Message**

- [ ] error message appears in a pop-up

- [x] an exception trace back is printed in the sublime console(Ctrl + \`)

- [ ] the command fails silently

```
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Sublime Text 3\Packages\PythonVoiceCodingPlugin\application\application.py", line 76, in respond_to_query
    s(view_information,query_description,extra)
  File "C:\Users\Admin\AppData\Roaming\Sublime Text 3\Packages\PythonVoiceCodingPlugin\queries\abstract\selection_query.py", line 80, in __call__
    self.result ,self.alternatives = self.handle_single(view_information,query_description, extra)
  File "C:\Users\Admin\AppData\Roaming\Sublime Text 3\Packages\PythonVoiceCodingPlugin\queries\select_part.py", line 41, in handle_single
    result = get_sub_index(second_origin,query_description["sub_index"]-1)
  File "C:\Users\Admin\AppData\Roaming\Sublime Text 3\Packages\PythonVoiceCodingPlugin\library\info.py", line 764, in get_sub_index
    candidates = get_subparts_of_string(root)
  File "C:\Users\Admin\AppData\Roaming\Sublime Text 3\Packages\PythonVoiceCodingPlugin\library\info.py", line 674, in get_subparts_of_string
    z = mean(y1,y2)
NameError: global name 'mean' is not defined
```

**Comment by mpourmpoulis** [comment]
0fcbc51877481349f38878509cb96068217c9694 tried to take care off of problems with strings that had prefixes like `r"something"` or `u"something"` but introduced a typo `mean`instead of `min` which was causing the exception. However it failed To take care off triple quoted strings causing wrong results. Both these problems should now be solved in the develop branch
